EntityFrameWorkCodeFirstApproach/EntityFrameWorkCodeFirstApproach/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EntityFrameWorkCodeFirstApproach.Models;
using Microsoft.WindowsAzure.Storage.Blob;
using EntityFrameWorkCodeFirstApproach.Services;
using Microsoft.AspNet.Identity;

namespace EntityFrameWorkCodeFirstApproach.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        BlobStorageServices blobStorageServices = new BlobStorageServices();

        // GET: Orders
        public async Task<ActionResult> Index()
        {
            var userId= User.Identity.GetUserId(); 
            if(!User.IsInRole("Admin"))
            return View(await db.Orders.Where(x => x.UserId == userId).ToListAsync());
            else
                return View(await db.Orders.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Order order, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid && file != null)
                {
                    var fileUrl = Upload(file);
                    if (!string.IsNullOrEmpty(fileUrl))
                    {
                        order.FileName = file.FileName;
                        order.CreatedDate = DateTime.UtcNow;
                        order.ModifiedDate = DateTime.UtcNow;
                        order.UserId = User.Identity.GetUserId();
                        order.Url = fileUrl;
                        db.Orders.Add(order);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }

                }
            }
            catch (Exception ex)
            {
                CloudBlobContainer blobContainer = blobStorageServices.GetCloudBlobContainer();
                CloudBlockBlob blob2 = blobContainer.GetBlockBlobReference("logs.txt");
                blob2.UploadText(ex.ToString());
                return View(order);

            }
            return View(order);
        }
      
        // GET: Orders/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "OrderId,OrderDescription,OrderStatus,CreatedDate,ModifiedDate,DeliveryAddress,UserId,Url,PrintingCost,TotalPages,DeliveryDate")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = await db.Orders.FindAsync(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Order order = await db.Orders.FindAsync(id);
            db.Orders.Remove(order);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private string Upload(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    CloudBlobContainer blobContainer = blobStorageServices.GetCloudBlobContainer();
                    CloudBlockBlob blob = blobContainer.GetBlockBlobReference(file.FileName);

                    // Upload content to the blob, which will create the blob if it does not already exist.  
                    blob.UploadFromStream(file.InputStream);
                    return blob.SnapshotQualifiedUri.ToString();
                }
            }
            catch (Exception ex)
            {
                CloudBlobContainer blobContainer = blobStorageServices.GetCloudBlobContainer();
                CloudBlockBlob blob2 = blobContainer.GetBlockBlobReference("myfile.txt");
                blob2.UploadText(ex.ToString());
                return string.Empty;

            }
            return string.Empty;
        }
    }
}

EntityFrameWorkCodeFirstApproach/EntityFrameWorkCodeFirstApproach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Printing Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Orders", "Index", "Orders")</li>
                    <li>@Html.ActionLink("Place Order", "Create", "Orders")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>